### ISSUE TITLE
Greatwork - is it ready to use?

### ISSUE THREAD

**Issue by lironsher** [afrihost/react-native-firebase-push-notifications#1]

**Comment by sacheen** [comment]
Hey @lironsher , it is almost ready to use. I just need to update the readme, provide some installation steps and document the usage. 
receiving push notifications work on both android and iOS. 
the method getInitialNotification works (get the notification when the app is closed), then the listener methods onNotificationOpened (app in background) and removeOnNotificationReceived (in app) works as well.

there is still much to do on this project, hopefully I will have some time in the up coming weeks to complete the above.

**Comment by lironsher** [comment]
did you implement android notification channels already? 
can you create a todo list and I will see what I can help with?

I think that the work that you have done have great value since v6 of rn-firebase.

**Comment by sacheen** [comment]
All functionality is there, one just needs to map the NativeModule functions in the index.js files.
The reason I went ahead with this is because of the rn-firebase v6.
It works in parallel with it (i.e you can install rnv6 and this and it works perfectly fine).

**Comment by lironsher** [comment]
Great work!
I couldn't understand "NativeModule functions in the index.js files."
can you give an example?

p.s. I post a link for this repo in StackOverflow

**Comment by sacheen** [comment]
Hey @lironsher - I'll give you an example of what I mean in this week, just have a bit of work I need to conclude first.

**Comment by sacheen** [comment]
@lironsher i've documented the installation and the current usages. I've also made a test app to make sure it works as intended.
