### ISSUE TITLE
Where do we think this module fits with rnfirebase.io?

### ISSUE THREAD

**Issue by spacesuitdiver** [afrihost/react-native-firebase-push-notifications#13]
We're upgrading RN to 0.63 which leads us to consider upgrading to rnfirebase.io version 6. It seems intervase has decided to drop the local notifications part of their library so we are looking at how to implement that. Where do we think this module fits with rnfirebase.io? https://rnfirebase.io/messaging/notifications

**Comment by sacheen** [comment]
Hi I made this library because of the upgrade to rnfirebase.io version 6 does not support push notifications (local and remote)
I still need to add in the functions and test that local notifications work.

**Comment by sacheen** [comment]
Just to add, we run V6 of rnfirebase.io with this library installed.

**Comment by spacesuitdiver** [comment]
Gotcha, are you using the v6 library for the other firebase features? That was part of my interest. We likely will give crashlytics a spin, we are using bugsnag currently. 

Also did you try just getting firebase working with the other push notification library https://github.com/zo0r/react-native-push-notification? That seems like another possibility but admittedly haven’t figured out how to glue that and v6 together or what might be missing.

**Comment by sacheen** [comment]
From what I understand (I think i've used this in another project https://github.com/zo0r/react-native-push-notification)
is that the library will generate a native token for android and a native token for iOS. So if you want to send a message to a specific device token you will need to setup the APN's services for Firebase and iOS (as they are different tokens and systems). What I did on the backend was created a factory service to send separate messages based on the type of token (iOS / Android) i.e if its Android send the message with firebases API and if its iOS send it using Apples APNs API

what firebase push notifications allow is to use a single token based system (Firebase will most likely have the Native iOS token mapped to the firebase token generated.) and you can use its console to send push messages to specific device tokens iOS / Android or blast a message to all devices.

We currently have crashlytics, analytics and perf from rnfirebase v6 and for the remote push notifications I use this library.
