### ISSUE TITLE
Displaying notifications in foreground

### ISSUE THREAD

**Issue by philanthalim** [afrihost/react-native-firebase-push-notifications#14]
I'm not able to display notifications in the foreground while sending a fcm notification from the test console in firebase. How do we modify the codes in our app.js to show notifications in the foreground?

**Comment by sacheen** [comment]
As far as I can recall, on both Android and iOS if you in App is running in the foreground you will not get a native push notification displayed. but the message and the data will be available on the `onNotification` listener.
So either you could receive the message and display it in your app as a banner or schedule a local notification (not implemented currently) however scheduling a local notification in app while its running does not feel like good UX practice

**Comment by nguyentrannhan** [comment]
i found an issue for the onNotificationListener function is called but not able to display notifications. Can i  do show notification when my app is running in the foreground?

**Comment by minh-dai** [comment]
i found an issue for the onNotificationListener function is called but not able to display notifications. Can i do show notification when my app is running in the foreground?

**Comment by sacheen** [comment]
If you need the notification to display on onNotificationListener - you should schedule a localNotification (as mentioned above - not implemented) as with both Android and iOS do not show notifications when the app is in the foreground (This is standard built in logic in the OS) 

for example  if you using WhatsApp / Instagram etc...if you in the app you will not get the push notification displayed to you (They just update the UI reflecting the new information) Imagine getting a push notification + the message in a messaging app? that wouldn't be a great experience.

but if you out of the app then you will get the notifications.

**Comment by kicketster** [comment]
@sacheen I am wondering why the notification functions are not getting called too. The functions have Logging statements in there but none of them are getting printed out(Both Foreground and Background). I put those functions in Splash screen before getting rerouted to Home. Am I using it right?

**Comment by sacheen** [comment]
You will need it to be present in the current navigation stack. I have my implementation on the home screen.

**Comment by justin-khoo** [comment]
@sacheen  I just moved it to the Home Screen and still isn't getting any log output when the app is in foreground. Do you have any tips to handle it? I get notification when the app is in background but not in foreground.
