### ISSUE TITLE
Notification is not working in the Foreground state (IOS)

### ISSUE THREAD

**Issue by subhani-ali** [afrihost/react-native-firebase-push-notifications#17]
I am using code below for push notification in foreground state:

```
notifications.onNotification((notificationOpen: any) => {
                    alert(`notification received: ${JSON.stringify(notificationOpen)}`)
                    console.log('foreground notification:', notificationOpen)
                })
```

alert is being shown in foreground, but how can I show alert just like what's app
I have setup all the necessary implementation in the `AppDelegate`

**Comment by sacheen** [comment]
Hi, You can use the localNotification function. its in the documentation.
