### ISSUE TITLE
Clear notification on Open

### ISSUE THREAD

**Issue by Atom1er** [afrihost/react-native-firebase-push-notifications#19]
Hello,
I am fairly new to this whole concept of push notifications. So please forgive me if it is obvious easy task. I followed the instructions and I am able to receive notifications from firebase and to create locals one too. But when I click on the notification it does not clear/remove it from the list. I can find anywhere where it shows how to do it. Please advice!

Thank You

**Comment by sacheen** [comment]
Hi the OS handles that by default.
