### ISSUE TITLE
iOS notification not playing any sound. Also not found any option to set it.

### ISSUE THREAD

**Issue by Anuj-Raghuvanshi** [afrihost/react-native-firebase-push-notifications#20]
All stuff of plugin is working perfectly. Receiving notification as well. But not any notification tone is playing. 
Also not found any documentation to set as well. Please suggest.
Thanks in advance!!

**Comment by Anuj-Raghuvanshi** [comment]
@sacheen @raymochi - Guys ?? Any workaround here ??

**Comment by UmNiK7** [comment]
@Anuj-Raghuvanshi just add "sound": "default" to your push notification object.
