### ISSUE TITLE
react-native-firebase-push-notifications not work in ios build 

### ISSUE THREAD

**Issue by BhalodiyaHappyDV** [afrihost/react-native-firebase-push-notifications#21]
No visible @interface for 'FIRMessaging' declares the selector 'sendMessage:to:withMessageID:timeToLive:'
![Screenshot 2021-03-04 at 11 21 00 AM](https://user-images.githubusercontent.com/69720303/109917723-cb92a700-7cdb-11eb-8fda-7f736d86df4b.png)

**Comment by sacheen** [comment]
if you using firebase v7+ this will be an issue on any version bellow 1.0.0 of this library.
I suggest  you upgrade to v1.0.0.
seems like you also pasted your screen shot string into the code:
![image](https://user-images.githubusercontent.com/1570598/111310060-4dcc8500-8665-11eb-994e-360cb7239903.png)
