### ISSUE TITLE
Not receiving push notification after reinstall of the application

### ISSUE THREAD

**Issue by amarjeet89** [afrihost/react-native-firebase-push-notifications#22]
Followed all the step given here but seeing weird issue  in ios -

- - Install fresh application in device  - it working as expected
- **- Uninstall and then reinstall the application in device - Notification not working** 
- - Uninstall then device restart and install application  - it's working as expected 

Verified in iPhone 8 plus ( iOS 14.4) & iPhone 11 (iOS 14.4)

React native version - 0.63.4

**Comment by sacheen** [comment]
please note that your token would have changed when you uninstall and re-install.
you will also have to make a request for permissions again, before the notifications can be delivered.
