### ISSUE TITLE
pod install fails after install react-native-firebase-push-notifications

### ISSUE THREAD

**Issue by alaaduksi** [afrihost/react-native-firebase-push-notifications#24]
I am trying to use "react-native-firebase-push-notifications" but when pod install or npx pod-install I am facing the below error: 

`[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 11.1.1, which depends on
      Firebase/CoreOnly (= 7.8.1)

    react-native-firebase-push-notifications (from `../node_modules/react-native-firebase-push-notifications`) was resolved to 1.0.0, which depends on
      Firebase/CoreOnly (~> 7.7.0)`

so I tried the below but nothing happened: 
- pod install --repo-update
- remove podfile.lock 
- remove Pods directory 

Any suggestion?

**Comment by pistonsky** [comment]
Fork this repo, and change this line in root `package.json` of this repo:
```
      "firebase": "~> 7.7.0"
```
to
```
      "firebase": "~> 7.7"
```
Then just use your fork in dependencies for your project like this:
```
    "react-native-firebase-push-notifications": "github:alaaduksi/react-native-firebase-push-notifications#master",
```

**Comment by alaaduksi** [comment]
@pistonsky I appreciate your reply, your reply solved my problem many thanks.

**Comment by alaaduksi** [comment]
Dear @pistonsky 

After installing new packages, I applied your advice again but today I got the same error! 

Advise me, please.

**Comment by alaaduksi** [comment]
I solve it after use:
`pod install --repo-update`
