### ISSUE TITLE
Remote notifications not working

### ISSUE THREAD

**Issue by ramkgunturu** [afrihost/react-native-firebase-push-notifications#28]
Hi,

I have followed the steps those are described on the npm page but I am unable to get the remote notifications when I tried from firebase in IOS or android. If this package supports getting the remote notifications, Could you please give any example to work around with this?

**Comment by kevilondo** [comment]
> Hi,
> 
> I have followed the steps those are described on the npm page but I am unable to get the remote notifications when I tried from firebase in IOS or android. If this package supports getting the remote notifications, Could you please give any example to work around with this?

Have you found a solution? I have the same problem now. Even worse, my application crashes when the notification is sent while using the app

**Comment by sacheen** [comment]
Hi,

Remote notifications are working -  you need to ensure you setup your firebase account correctly.
ensure that you follow all the setup steps in the instructions.

Here is a sample app: https://github.com/afrihost/firebasePushTest that implements this library. 

all features work as intended.
