### ISSUE TITLE
Found this library useful - some questions about it

### ISSUE THREAD

**Issue by iarmankhan** [afrihost/react-native-firebase-push-notifications#4]
Hello, 
So I just found this library while searching for some proper notification library that can work without any errors for react native.
I've ran your given example app and it did receive notification so I can say it's working. Haven't tested this on release app yet.
So my question is, is it ready for use in production app (small apps that I build for practice and portfolio)? I've seen multiple libraries that work very well in development but fails in production.

Also, what is the status of Local notification and scheduled local notification (like one notification every 24 hour) 

Also what is the format of notifcation data being sent, (I use my personal server to send notification via fcm API) so can you provide sample notification data object for android.

Thank you. Keep up the good work

**Comment by sacheen** [comment]
Hi,
1. Yes we are using it in production on our Afrihost Mobile App. So it should be good for production.
2. Work still needs to be done to get local notifications tested - there is no ETA on it.
3. The format will be the same as the FCM message you send from the API

**Comment by iarmankhan** [comment]
Okay it seems promising, what is the status of deep linking ? 
Are you working on that? It would be awesome if you can enable that. Also I'm going to use this for my current project (production) Hope it all works good.

**Comment by sacheen** [comment]
Deep Linking is beyond the scope of "Notifications" 
There is a project V6 of invertase implementation of Deep Linking that will work side by side with this project. (https://invertase.io/oss/react-native-firebase/v6/dynamic-links)

**Comment by iarmankhan** [comment]
Okay I'll check on that! Thank you. ✨
