### ISSUE TITLE
A problem occurred configuring project ':react-native-firebase-push-notifications'. > Configuration with name 'compile' not found.

### ISSUE THREAD

**Issue by hafiz-sameed** [afrihost/react-native-firebase-push-notifications#47]
Here's version of the packages
`
 "react": "18.0.0",
    "react-native": "0.69.0",
    "react-native-firebase-push-notifications": "^2.0.2"
`

I installed react-native-firebase-push-notifications and after that I ran `npx react-native run-android` but, I am getting this error.

`
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/hafizsameed/Documents/right-hand/rn-0.69.0-project/app/node_modules/react-native-firebase-push-notifications/android/build.gradle' line: 179

* What went wrong:
A problem occurred configuring project ':react-native-firebase-push-notifications'.
> Configuration with name 'compile' not found.
`

my android/build.gradle 
`
 repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.1.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
`
my app/build.gradle (added code)
`
    apply plugin: 'com.google.gms.google-services'

    implementation 'com.google.firebase:firebase-analytics:17.2.2'
`

**Comment by mvltivitamin** [comment]
Facing the same issue, did you manage to find a solution?

**Comment by hafiz-sameed** [comment]
@mvltivitamin didn't found a proper solution but, got a workaround.
change this
` classpath += files(project.getConfigurations().getByName('compile').asList())`
to
` classpath += files(project.getConfigurations().getByName('implementation').asList())`
and add `configurations.implementation.setCanBeResolved(true)` before afterEvaluate configuration in node_modules/react-native-firebase-push-notifications/android/build.gradle.

I don't recommend this solution but, it does the job.
