### ISSUE TITLE
Notification not working when the application is in foreground

### ISSUE THREAD

**Issue by kicketster** [afrihost/react-native-firebase-push-notifications#9]
I have successfully tested the application to receive "test notification" from firebase when the app is in background. However, when the application is in foreground, I never receive any notification. 

Is there any particular permission needs to be added to AndroidManifest in order for it to work? 

Is anyone facing the same issue? Please help!

**Comment by sacheen** [comment]
Hi,

This is normal behaviour for both Android and iOS see docs section:
```
  onNotificationListener = () => {
    //remember to remove the listener on un mount
    //this gets triggered when the application is in the forground/runnning
    //for android make sure you manifest is setup - else this wont work
    //Android will not have any info set on the notification properties (title, subtitle, etc..), but _data will still contain information
    this.removeOnNotification = notifications.onNotification(notification => {
      //do something with the notification
      console.log("onNotification", notification)
    })
  }
```

**Comment by kicketster** [comment]
@sacheen 
Is there anyway to receive the notification? When the app is in foreground, I don't even see "Console.log()" printing out the result. The function is not even getting invoked. 

"//for android make sure you manifest is setup - else this wont work" 
How should I set it up in the manifest?

**Comment by sacheen** [comment]
Hi, You can perhaps try schedule a local notification when listening with `onNotificationListener `.
I have not had time though to implement the local notification as yet, hopefully will have time in the coming weeks.

**Comment by kicketster** [comment]
@sacheen thank you. I am looking forward to it. This would be a really great feature.

**Comment by thuongtv-vn** [comment]
Hi, I have the same issue on Android, when the application in the foreground. The "onNotification" callback never called. Manifest is setup. Do you know why?

**Comment by sacheen** [comment]
Hi @thuongtv-vn is the result of console.log in the  onNotificationListener not being called? or is there a result and its not showing the message? 
if its the latter, then this is the desired behaviour as remote notifications do not display while the app is in the foreground.

**Comment by thuongtv-vn** [comment]
Hi @sacheen 
the onNotificationListener not being called, that's why console.log nothing.

**Comment by sacheen** [comment]
could you quickly install and configure : https://github.com/afrihost/firebasePushTest
to see if you experiencing the same?
I'm running it in production and working as expected.

**Comment by thuongtv-vn** [comment]
Hi @sacheen 
Thank you! It is working now. I have followed README and configurated the manifest file not completed. 

I have another question. In case we manual setup on android. Do we need to add RNFirebaseNotificationPackage or only FirebasePushNotificationsPackage?
